### ISSUE TITLE
Still Working in 2022 Builds?

### ISSUE THREAD

**Issue by christopherdenny** [erlsta/homeassistant-lovelace-birthday-reminder-card#10]
Is this still working in the latest 2022 builds of Home Assistant? I have tried using it a resource, but I always end up getting an error message on the Dashboard "Custom element doesn't exist: birthday-card". It may be as asimple as me giving the wrong URL, but I have tried everything. 

I have the birthday-card folder in the addons folder, which is off root. (/addons/birthday-card/birthday-card.js?v=1.2001) 

-Chris

**Comment by onebyside** [comment]
Works great here
place:

www/plugins/birthday-card/birthday-card.js

Resources:      /local/plugins/birthday-card/birthday-card.js
After adding dates edit      /local/plugins/birthday-card/birthday-card.js?v=1.001

refresh

**Comment by christopherdenny** [comment]
Thanks for the reply.

I do not have a www folder, so my addons folder is off the root folder. (/addons/birthday-card/birthday-card.js ?)

Maybe I am not understanding the second step of editing the file. Amd I just adding the "?v-1.001" to the end of the resource URL?

-Chris

**Comment by christopherdenny** [comment]
I finally have it running! I had to create the www folder, and then I could use the same URL the author used.

**Comment by onebyside** [comment]
Everytime  you add a person/s or date/s you have to change the version then refreshOn Mar 16, 2022 8:48 AM, christopherdenny ***@***.***> wrote:
Thanks for the reply.
I do not have a www folder, so my addons folder is off the root folder. (/addons/birthday-card/birthday-card.js ?)
Maybe I am not understanding the second step of editing the file. Amd I just adding the "?v-1.001" to the end of the resource URL?
-Chris
