### ISSUE TITLE
1 month off

### ISSUE THREAD

**Issue by r3mcos3** [erlsta/homeassistant-lovelace-birthday-reminder-card#2]
Hi, 

i found a issue the month is 1 month off 

![1 month off](https://user-images.githubusercontent.com/45529818/54088657-ae32d880-4360-11e9-9067-89e08ccd355c.png)

**Comment by erlsta** [comment]
Thanks! Yes, I discovered this bug myself. The code was corrected only a few minutes after i released the last version, so I just sneaked in the correction without changing the version number, thinking that no-one had managed to download it yet. The code should be fine now. Sorry!

**Comment by r3mcos3** [comment]
Ok thnx gonna update tonight 👍

**Comment by r3mcos3** [comment]
hi sir,

i've updated the .js file 
but i'ts still 1 month off. 
The month January is showing as month "0"

keep up the good work!
 
**** I speaked to soon after another reboot it's working like a charm***

**Comment by erlsta** [comment]
Great! I was about to ask if you remembered to change the version number. :-)

**Comment by r3mcos3** [comment]
Now you saying that, I actually did not! 

But it works now.
